// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgGx3udotsMjXhv9e5ILJtyzOuxS55z1E',
    appId: '1:879213250093:android:6280e219b0c697048fdaa4',
    messagingSenderId: '879213250093',
    projectId: 'mynotes-flutter-project-54d22',
    storageBucket: 'mynotes-flutter-project-54d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeM8AfF8TzohSmUgrGKvl7ItxD9Elc46E',
    appId: '1:879213250093:ios:6450ec1c2e94a88d8fdaa4',
    messagingSenderId: '879213250093',
    projectId: 'mynotes-flutter-project-54d22',
    storageBucket: 'mynotes-flutter-project-54d22.appspot.com',
    iosClientId: '879213250093-g27sckbec605kh5a9gt66updv93a728g.apps.googleusercontent.com',
    iosBundleId: 'com.domainName.mynotes',
  );
}
